export const recentActivities = [
  {
    id: 1,
    title: "John Doe completed 'Send Weekly Report'",
    date: new Date('2024-01-20'),
    status: 'Completed',
    description:
      "John Doe submitted the weekly report on time. The report contains updates on project progress and upcoming tasks, ensuring stakeholders are informed about the project's status and future plans.",
    assignedTo: 'John Doe',
    priority: 'High',
    category: 'Weekly Reports',
    link: 'activity',
  },
  {
    id: 2,
    title: "New task added: 'Client Presentation'",
    date: new Date('2024-01-18'),
    status: 'Pending',
    description:
      'A new task has been added to prepare for the client presentation scheduled for next week. This task involves gathering necessary materials and coordinating with team members to ensure a successful presentation.',
    assignedTo: 'Team Member 1',
    priority: 'Medium',
    category: 'Tasks',
    link: 'activity',
  },
  {
    id: 3,
    title: 'Client Meeting scheduled for tomorrow',
    date: new Date('2024-01-22'),
    status: 'Scheduled',
    description:
      'A meeting with the client has been scheduled to discuss project updates and upcoming tasks. This meeting is crucial for maintaining open communication and addressing any concerns or questions the client may have.',
    assignedTo: 'Project Manager',
    priority: 'High',
    category: 'Meetings',
    link: 'activity',
  },
  {
    id: 4,
    title: 'Received feedback from stakeholders',
    date: new Date('2024-01-16'),
    status: 'Received',
    description:
      'Feedback has been received from stakeholders regarding the latest project milestone. This feedback will be reviewed and used to make necessary adjustments to ensure project success and stakeholder satisfaction.',
    assignedTo: 'Project Team',
    priority: 'Low',
    category: 'Feedback',
    link: 'activity',
  },
  {
    id: 5,
    title: 'Completed training session on new tool',
    date: new Date('2024-01-14'),
    status: 'Completed',
    description:
      'A training session on the new project management tool has been successfully completed. Team members are now equipped with the knowledge and skills needed to effectively utilize the tool in project management tasks.',
    assignedTo: 'All Team Members',
    priority: 'High',
    category: 'Training',
    link: 'activity',
  },
  {
    id: 6,
    title: 'Reviewed project proposal with team',
    date: new Date('2024-01-12'),
    status: 'In Progress',
    description:
      'The project proposal is currently under review with the project team for feedback and revisions. This collaborative effort ensures that the proposal meets all requirements and aligns with project objectives before submission.',
    assignedTo: 'Project Team',
    priority: 'High',
    category: 'Proposal',
    link: 'activity',
  },
  {
    id: 7,
    title: 'Updated project timeline',
    date: new Date('2024-01-10'),
    status: 'Completed',
    description:
      'The project timeline has been updated to reflect recent changes and milestones. This updated timeline provides clarity on project progress and helps stakeholders anticipate key project milestones and deliverables.',
    assignedTo: 'Project Manager',
    priority: 'Medium',
    category: 'Project Management',
    link: 'activity',
  },
  {
    id: 8,
    title: 'Received approval for project budget',
    date: new Date('2024-01-08'),
    status: 'Approved',
    description:
      'Approval has been obtained for the project budget, allowing project activities to proceed as planned. This approval ensures that sufficient resources are allocated to project tasks and that financial constraints are addressed.',
    assignedTo: 'Finance Department',
    priority: 'High',
    category: 'Finance',
    link: 'activity',
  },
  {
    id: 9,
    title: 'Client demo scheduled for next week',
    date: new Date('2024-01-26'),
    status: 'Scheduled',
    description:
      'A client demonstration is scheduled for next week to showcase project progress and gather feedback. This demo is an opportunity to demonstrate project accomplishments and address any client concerns or requests.',
    assignedTo: 'Project Team',
    priority: 'High',
    category: 'Client Demo',
    link: 'activity',
  },
  {
    id: 10,
    title: 'Task assigned to team member',
    date: new Date('2024-01-05'),
    status: 'Assigned',
    description:
      'A new task has been assigned to a team member for completion by the specified deadline. Clear assignment of tasks ensures accountability and progress towards project goals.',
    assignedTo: 'Team Member 2',
    priority: 'Medium',
    category: 'Tasks',
    link: 'activity',
  },
];

export const quickStats = [
  {
    id: 1,
    value: 15,
    title: 'Total Tasks',
    backgroundColor: '#8FCDFE',
  },
  {
    id: 2,
    value: 8,
    title: 'Completed',
    backgroundColor: '#96FE8F',
  },
  {
    id: 3,
    value: 3,
    title: 'Overdue',
    backgroundColor: '#FEBE8F',
  },
  {
    id: 4,
    value: 4,
    title: 'In Progress',
    backgroundColor: '#E5FE8F',
  },
];

export const tasks = [
  {
    id: 1,
    title: 'Review Project Proposal',
    description: 'Review the project proposal and provide feedback.',
    deadline: new Date('2024-02-28'),
    assignedTo: 'Project Team',
    priority: 'High',
    status: 'Pending',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
  {
    id: 2,
    title: 'Prepare Meeting Agenda',
    description: 'Prepare the agenda for the upcoming project meeting.',
    deadline: new Date('2024-02-25'),
    assignedTo: 'Project Manager',
    priority: 'Medium',
    status: 'In Progress',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
  {
    id: 3,
    title: 'Send Weekly Report',
    description: 'Compile and send the weekly project progress report.',
    deadline: new Date('2024-02-27'),
    assignedTo: 'John Doe',
    priority: 'High',
    status: 'Pending',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
  {
    id: 4,
    title: 'Client Call at 2 PM',
    description: 'Attend the scheduled client call at 2 PM.',
    deadline: new Date('2024-02-24'),
    assignedTo: 'Jane Smith',
    priority: 'High',
    status: 'In Progress',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
  {
    id: 5,
    title: 'Update User Interface',
    description: 'Implement UI enhancements based on client feedback.',
    deadline: new Date('2024-03-05'),
    assignedTo: 'UI Development Team',
    priority: 'High',
    status: 'Pending',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
  {
    id: 6,
    title: 'Optimize Database Queries',
    description: 'Optimize database queries for improved performance.',
    deadline: new Date('2024-03-10'),
    assignedTo: 'Database Team',
    priority: 'Medium',
    status: 'In Progress',
    link: 'tasks',
    img1: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
    img2: 'https://images.unsplash.com/photo-1488998527040-85054a85150e',
    img3: 'https://images.unsplash.com/profile-1441298803695-accd94000cac?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img4: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img5: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
    img6: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=32085a077889586df88bfbe406692202',
  },
];

export const projects = [
  {
    id: 1,
    title: 'Project Name: XYZ Project',
    description:
      'The XYZ Project aims to develop an AI-powered virtual assistant capable of natural language understanding and task automation. Tasks include implementing machine learning algorithms, designing conversational interfaces, and integrating with various APIs.',
    status: 'Completed',
    teamMembers: ['Alice Johnson', 'Bob Brown', 'Charlie Davis'],
    link: 'projects',
    subtitle1: 'Agenda',
    subtitle2: 'Conclusion',
    imageUrl1: 'https://images.unsplash.com/photo-1625812346416-ae997372d98e',
    imageUrl2: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74',
    keypoints1: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    ],
    keypoints2: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
  },
  {
    id: 2,
    title: 'Project Name: PQR Project',
    description:
      'The PQR Project focuses on building a blockchain-based decentralized application (DApp) for supply chain management. Future tasks involve smart contract development, secure data storage, and interoperability with existing systems.',
    status: 'In Progress',
    teamMembers: ['David Wilson', 'Emma White'],
    link: 'projects',
    subtitle1: 'Agenda',
    subtitle2: 'Conclusion',
    imageUrl1: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
    imageUrl2: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d',
    keypoints1: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    ],
    keypoints2: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
  },
  {
    id: 3,
    title: 'Project Name: LMN Project',
    description:
      'The LMN Project is dedicated to developing a scalable microservices architecture for an e-commerce platform. Future tasks include containerization with Docker, orchestration with Kubernetes, and implementing RESTful APIs.',
    status: 'Planned',
    teamMembers: ['Frank Robinson', 'Gina Martinez', 'Harry Young'],
    link: 'projects',
    subtitle1: 'Agenda',
    subtitle2: 'Conclusion',
    imageUrl1: 'https://images.unsplash.com/photo-1703756847840-0eaed63ac9db',
    imageUrl2: 'https://images.unsplash.com/photo-1543286386-713bdd548da4',
    keypoints1: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    ],
    keypoints2: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
  },
  {
    id: 4,
    title: 'Project Name: RST Project',
    description:
      'The RST Project aims to create a next-generation mobile application for augmented reality experiences. Future tasks include ARKit integration, 3D model rendering, and real-time environment mapping.',
    status: 'On Hold',
    teamMembers: ['Ivy Lee'],
    link: 'projects',
    subtitle1: 'Agenda',
    subtitle2: 'Conclusion',
    imageUrl1: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7',
    imageUrl2: 'https://images.unsplash.com/photo-1559526324-593bc073d938',
    keypoints1: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    ],
    keypoints2: [
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    ],
  },
];

export const notifications = [
  {
    Message:
      "Reminder: Tomorrow's sprint planning meeting for the XYZ Project is scheduled at 10:00 AM.",
  },
  {
    Message:
      'Action Required: The deadline for submitting project deliverables for the LMN Project is approaching',
  },
];

export const mail = [
  {
    Message: ' Urgent: Update Required - ABC Project Milestone',
  },
  {
    Message: 'Action Required: Review Meeting Schedule - XYZ Project',
  },
  {
    Message: 'Upcoming Deadline - PQR Project Task',
  },
  {
    Message: 'Schedule Change - LMN Project Meeting',
  },
  {
    Message: 'Important: RST Project Update',
  },
];
